### ISSUE TITLE
Passionate Pilgrim: stanza 17 seems out of place

### ISSUE THREAD

**Issue by samdutton** [severdia/PlayShakespeare.com-XML#7]
https://github.com/severdia/PlayShakespeare.com-XML/blob/a9960d39133deff7f821a95e5342bb4faa61cb1b/playshakespeare_editions/ps_passionate_pilgrim.xml#L355

(The stanza  between 13 and 14 is numbered 17, and there is no stanza 17 [here](https://github.com/severdia/PlayShakespeare.com-XML/blob/a9960d39133deff7f821a95e5342bb4faa61cb1b/playshakespeare_editions/ps_passionate_pilgrim.xml#L541).)

Great project by the way — thank you!

**Comment by severdia** [comment]
@samdutton You are absolutely correct. I've just pushed version 5 of the editions, which corrects this and adds other improvements/corrections. Thanks!
